"""initial migration

Revision ID: 40f0a4c34330
Revises: 
Create Date: 2024-10-18 18:02:32.098822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f0a4c34330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('module_code', sa.String(length=20), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_is_completed'), ['is_completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_module_code'), ['module_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_assessment_title'), ['title'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_title'))
        batch_op.drop_index(batch_op.f('ix_assessment_module_code'))
        batch_op.drop_index(batch_op.f('ix_assessment_is_completed'))

    op.drop_table('assessment')
    # ### end Alembic commands ###
